services:
  pulseorperish:
    image: ghcr.io/jerome-labidurie/pulseorperish:latest
    container_name: pulseorperish
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      POP_PASSWORD: "mysecret"
      POP_LISTEN: ":8080"
      POP_INTERVAL: "24h"
      POP_DRY_RUN: "false"
      POP_DATA_DIRS: "/data"
      POP_STATE_DIR: "/state"
      POP_LOG_LEVEL: "info"
    volumes:
      - ./demo-data:/data
      - ./demo-state:/state
